# Generated by Django 4.1.7 on 2023-03-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='weight_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='WeightClasses', to='armwrestling_app.weightclass'),
        ),
    ]
