# Generated by Django 4.1.7 on 2023-03-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0002_alter_competitor_weight_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='weight_class',
        ),
    ]
