# Generated by Django 4.1.7 on 2023-03-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0004_league_tournament_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='weight_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.weightclass'),
        ),
    ]
