# Generated by Django 4.1.7 on 2023-03-28 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0012_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='country',
            field=models.CharField(default='Russia', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 18, 2, 20, 277596)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 18, 2, 20, 277681)),
        ),
    ]
