# Generated by Django 4.1.7 on 2023-04-05 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0013_competitor_country_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='kFactor',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='competitor',
            name='mode',
            field=models.CharField(blank=True, default='competitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 17, 27, 17, 815236)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 17, 27, 17, 815298)),
        ),
    ]
