# Generated by Django 4.1.7 on 2023-04-06 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0016_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 11, 33, 24, 433988)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 11, 33, 24, 434013)),
        ),
    ]
