# Generated by Django 4.1.7 on 2023-04-08 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0018_tournament_is_started_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 14, 22, 50, 560097)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 14, 22, 50, 560150)),
        ),
        migrations.CreateModel(
            name='TournamentWeightClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.tournament')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.weightclass')),
            ],
        ),
    ]
