# Generated by Django 4.1.7 on 2023-04-08 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0019_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightclass',
            name='lower_weight_limit',
        ),
        migrations.RemoveField(
            model_name='weightclass',
            name='upper_weight_limit',
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 0, 31, 574915)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 0, 31, 574992)),
        ),
    ]
