# Generated by Django 4.1.7 on 2023-04-08 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0021_competitor_weight_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='weight_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.weightclass'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 19, 19, 20, 525723)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 19, 19, 20, 525781)),
        ),
    ]
