# Generated by Django 4.1.7 on 2023-10-16 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0025_alter_league_president_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='average_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 10, 51, 46, 170557)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 10, 51, 46, 170557)),
        ),
    ]
