# Generated by Django 4.1.7 on 2023-10-17 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0028_competitor_phone_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='competitor',
            name='description',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/competitors_userpictures'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 56, 23, 666490)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 56, 23, 666490)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/tournaments_banners'),
        ),
    ]
