# Generated by Django 4.1.7 on 2023-10-17 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0029_competitor_city_competitor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='birthdate',
            field=models.DateField(blank=True, default='2023-10-17'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='career_start_date',
            field=models.DateField(blank=True, default='2023-10-17'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 56, 39, 560317)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 56, 39, 560317)),
        ),
    ]
