# Generated by Django 4.1.7 on 2023-10-17 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0030_competitor_birthdate_competitor_career_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='career_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 57, 48, 701786)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 57, 48, 701786)),
        ),
    ]
