# Generated by Django 4.1.7 on 2023-10-27 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0031_alter_competitor_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='email',
            field=models.CharField(blank=True, default='', max_length=99),
        ),
        migrations.AddField(
            model_name='league',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 18, 59, 2, 141552)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 18, 59, 2, 141552)),
        ),
    ]
