# Generated by Django 4.1.7 on 2023-10-17 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0031_alter_competitor_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 31, 3, 928419)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 31, 3, 928435)),
        ),
    ]
