# Generated by Django 4.1.7 on 2023-10-28 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0032_league_creation_date_league_email_league_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='level',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 40, 57, 78852)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 40, 57, 78852)),
        ),
    ]
