# Generated by Django 4.1.7 on 2023-10-29 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0033_tournament_level_tournament_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 12, 25, 52, 290741)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 12, 25, 52, 290741)),
        ),
    ]
