# Generated by Django 4.1.7 on 2023-11-05 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0034_tournamentregistration_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=None)),
                ('text', models.TextField()),
                ('date', models.DateField(blank=True, default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 11, 55, 40, 271514)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 11, 55, 40, 271514)),
        ),
        migrations.CreateModel(
            name='TournamentReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armwrestling_app.review')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.tournament')),
            ],
            bases=('armwrestling_app.review',),
        ),
        migrations.CreateModel(
            name='LeagueReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='armwrestling_app.review')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.league')),
            ],
            bases=('armwrestling_app.review',),
        ),
    ]
