# Generated by Django 4.1.7 on 2023-11-07 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0036_review_verified_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 14, 54, 11, 235680)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 14, 54, 11, 235680)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='main_referee',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_main_referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='main_secretary',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_main_secretary', to=settings.AUTH_USER_MODEL),
        ),
    ]
