# Generated by Django 4.1.7 on 2023-11-07 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0037_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 14, 56, 20, 342631)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 14, 56, 20, 342631)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='league',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.league'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='media/tournaments_banners'),
        ),
    ]
