# Generated by Django 4.1.7 on 2023-11-13 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0043_notification_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 0, 58, 558460)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 0, 58, 558460)),
        ),
    ]
