# Generated by Django 4.1.7 on 2023-11-21 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0045_tournament_biceps_tournament_crossbar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='biceps',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='crossbar',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='grip',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='militarypress',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='press',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='shaft',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='side',
        ),
        migrations.AddField(
            model_name='competitor',
            name='biceps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='crossbar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='grip',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='hand',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='militarypress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='press',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='shaft',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='side',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 12, 49, 52, 587570)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 12, 49, 52, 587570)),
        ),
    ]
