# Generated by Django 4.1.7 on 2023-11-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0033_alter_match_created_at_alter_match_date'),
        ('armwrestling_app', '0046_remove_tournament_biceps_remove_tournament_crossbar_and_more'),
    ]

    operations = [
    ]
