# Generated by Django 4.1.7 on 2023-11-26 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0049_alter_match_created_at_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 11, 7, 48, 554643)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 11, 7, 48, 554643)),
        ),
    ]
