# Generated by Django 4.1.7 on 2023-11-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0052_league_banner_league_logo_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='photo',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/league_logo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 8, 15, 577696)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 8, 15, 577696)),
        ),
    ]
