# Generated by Django 4.1.7 on 2023-11-26 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0053_rename_photo_tournament_banner_tournament_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 18, 34, 701721)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 18, 34, 701721)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/tournaments_logo'),
        ),
    ]
