# Generated by Django 4.1.7 on 2023-11-28 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0054_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='afisha',
            field=models.ImageField(blank=True, upload_to='media/tournaments_afisha'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 57, 27, 182780)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 57, 27, 182780)),
        ),
    ]
