# Generated by Django 4.1.7 on 2023-11-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0047_merge_20231124_1230'),
        ('armwrestling_app', '0054_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
    ]
