# Generated by Django 4.1.7 on 2023-11-28 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0056_tournamentweightclasses_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 16, 36, 4, 715478)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 16, 36, 4, 715478)),
        ),
        migrations.AlterField(
            model_name='tournamentweightclasses',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
