# Generated by Django 4.1.7 on 2023-11-29 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0057_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 21, 58, 45, 687920)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 21, 58, 45, 687920)),
        ),
    ]
