# Generated by Django 4.1.7 on 2023-12-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0055_merge_20231127_0927'),
        ('armwrestling_app', '0058_supportrequest_alter_match_created_at_and_more'),
    ]

    operations = [
    ]
