# Generated by Django 4.1.7 on 2023-12-12 08:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0060_team_banner_team_logo_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_team', to='armwrestling_app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 11, 2, 28, 690079)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 11, 2, 28, 691079)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 11, 2, 28, 687080)),
        ),
        migrations.AlterField(
            model_name='team',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
