# Generated by Django 4.1.7 on 2023-12-14 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0061_competitor_team_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecompetitor',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 12, 13, 8, 903053)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 12, 13, 8, 903053)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 12, 13, 8, 900038)),
        ),
    ]
