# Generated by Django 4.1.7 on 2023-12-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0062_leaguecompetitor_status_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 14, 23, 22, 209876)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 14, 23, 22, 209876)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 14, 23, 22, 209876)),
        ),
    ]
