# Generated by Django 4.1.7 on 2023-12-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0059_merge_20231208_1515'),
        ('armwrestling_app', '0064_alter_match_created_at_alter_match_date_and_more'),
    ]

    operations = [
    ]
