# Generated by Django 4.1.7 on 2024-01-03 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0065_teamcompetitor_role_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcompetitor',
            name='role',
        ),
        migrations.AddField(
            model_name='leaguecompetitor',
            name='role',
            field=models.CharField(default='competitor', max_length=35),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 54, 375733)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 54, 375733)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 54, 371730)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 54, 373733)),
        ),
    ]
