# Generated by Django 4.1.7 on 2024-01-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0066_remove_teamcompetitor_role_leaguecompetitor_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecompetitor',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 17, 51, 30, 269584)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 17, 51, 30, 269584)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 17, 51, 30, 265585)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 17, 51, 30, 267587)),
        ),
    ]
