# Generated by Django 4.1.7 on 2024-01-17 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0068_tournamentregistration_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='weight',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 14, 34, 11, 798130)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 14, 34, 11, 798130)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 14, 34, 11, 782504)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 14, 34, 11, 782504)),
        ),
    ]
