# Generated by Django 4.1.7 on 2024-01-18 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0070_tournamentregistration_paid_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='hand',
            field=models.CharField(blank=True, default='left', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 10, 7, 235047)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 10, 7, 235047)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 10, 7, 235047)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 10, 7, 235047)),
        ),
    ]
