# Generated by Django 4.1.7 on 2024-02-22 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0071_tournamentregistration_hand_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 9, 52, 36, 744626)),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 9, 52, 36, 744626)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 9, 52, 36, 738618)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 9, 52, 36, 743626)),
        ),
        migrations.CreateModel(
            name='TournamentParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='default', max_length=30)),
                ('tables', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armwrestling_app.tournament')),
            ],
        ),
    ]
