# Generated by Django 4.1.7 on 2024-01-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0066_alter_match_created_at_alter_match_date_and_more'),
        ('armwrestling_app', '0071_tournamentregistration_hand_alter_match_created_at_and_more'),
    ]

    operations = [
    ]
