# Generated by Django 4.1.7 on 2024-03-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0072_merge_20240122_1239'),
        ('armwrestling_app', '0074_match_first_competitor_result_rating_and_more'),
    ]

    operations = [
    ]
