# Generated by Django 4.1.7 on 2024-04-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0076_alter_match_created_at_alter_match_date_and_more'),
        ('armwrestling_app', '0076_competitor_elo_rating_right_alter_team_created_at_and_more'),
    ]

    operations = [
    ]
