# Generated by Django 4.1.7 on 2024-04-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0077_match_round_alter_team_created_at_and_more'),
        ('armwrestling_app', '0077_merge_20240408_0951'),
    ]

    operations = [
    ]
