# Generated by Django 4.1.7 on 2024-06-19 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0077_match_round_alter_team_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentweightclasses',
            name='compeleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 10, 39, 25, 752628)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 10, 39, 25, 756664)),
        ),
    ]
