# Generated by Django 4.1.7 on 2024-06-20 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0078_tournamentweightclasses_compeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentweightclasses',
            name='roundsCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 9, 45, 53, 546543)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 9, 45, 53, 552776)),
        ),
    ]
