# Generated by Django 4.1.7 on 2024-06-20 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0079_tournamentweightclasses_roundscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentweightclasses',
            old_name='compeleted',
            new_name='completed_left',
        ),
        migrations.AddField(
            model_name='tournamentweightclasses',
            name='completed_right',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 11, 29, 41, 509683)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 11, 29, 41, 519201)),
        ),
    ]
