# Generated by Django 4.1.7 on 2024-06-23 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armwrestling_app', '0080_rename_compeleted_tournamentweightclasses_completed_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='grid',
            field=models.CharField(blank=True, default='upper', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 10, 32, 51, 157470)),
        ),
        migrations.AlterField(
            model_name='teamcompetitor',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 10, 32, 51, 161052)),
        ),
    ]
